### ISSUE TITLE
Bus

### ISSUE THREAD

**Issue by xtrasmal** [matthiasnoback/high-quality-bundles-project#2]
@matthiasnoback 

Any plans of using the Symfony2 Tactician Bundle instead of the Simple bus? The tactician bundle supports multiple buses, is based on Ross Tuck's PHP league Tactician library and is very easily configurable for new comers. 

Well anyways, see you on Monday.

**Comment by matthiasnoback** [comment]
Hi there, thanks for opening this issue. A little bit of history as an answer: I initially created SimpleBus for my Hexagonal architecture training. The command bus part of SimpleBus is pretty much the same as it is in Tactician, and that's because I frequently discussed its design with Ross Tuck, the creator of Tactician ;) The thing is, for my training I also needed an event mechanism, which at the time was not offered by Tactician (and I don't believe it is nowadays). So SimpleBus also contains that: classes and interfaces for creating an event bus and event subscribers. Finally, for the last "chapter" of the training, I wanted to do something with asynchronous handling of commands and events, so I started working on some generic tools for that. These should make it very easy for people to start using RabbitMQ (which is quite popular, but it could be any other message queue software) on the day after the training. Also, since the training is Symfony-oriented, everything should be working out-of-the-box and very easily within a Symfony project. 

So SimpleBus was originally created to facilitate this training and Tactician simply doesn't offer every feature I need to discuss all the concepts of the hexagonal/cqrs architecture. So, I guess I'm not going to use Tactician in my training project. Unless these reasons disappear sometime in the future and everybody uses Tactician anyway ;)
